use_frameworks!
platform :ios, '8.0'

target 'SplitSlider_Example' do
  pod 'SplitSlider', :path => '../'

  target 'SplitSlider_Tests' do
    inherit! :search_paths

  pod 'Quick'#, '~> 1.3.2'
  pod 'Nimble', '~> 7.3.1'
  end
end
